### ISSUE TITLE
[mozbitbar-30] Do not hide error details when wrapping and re-raising exceptions.

### ISSUE THREAD

**Issue by bclary** [worldomonation/mozbitbar#61]
This is not an exhaustive list but are just examples...

<https://github.com/worldomonation/mozbitbar/blob/master/mozbitbar/configuration.py#L41> catches the AssertionErrors and re-raises a CredentialException with a generic failure message. It loses any information regarding which condition actually failed.

We should use the ability to pass a message in the AssertionError to tell exactly what failed. For example

`assert (self.user_name and self.user_password) or self.api_key, "Missing Credentials"`
`assert self.url, "Missing testdroid cloud url"`

then capture that in the except clause and log it and perhaps add it to the CredentialException message.

<https://github.com/worldomonation/mozbitbar/blob/master/mozbitbar/configuration.py#L54> catches any exception which might have occurred during the call to `self.client.get_me()` and raises a CredentialException claiming that the reason was due to invalid credentials, when any number of different errors might have occurred. We should not lose the information as to the real cause of the exception.

Here we should look to <https://github.com/bitbar/testdroid-api-client-python/blob/master/testdroid/__init__.py#L32> and extract the error message and status_code of the error.

Ditto for elsewhere in the code.

**Comment by worldomonation** [comment]
I think that's fair. There are a bunch of locations where I hadn't gone around to properly do exceptions, being carried over from the initial prototyping days.

What I could do for this bug is to work in conjunction with #59 (add logging support) to rework the exception handling structure, and return the error code whenever possible.

**Comment by bclary** [comment]
Sounds good. Feel free to dupe it.

**Comment by worldomonation** [comment]
#88 makes some changes:

- if error is raised by Testdroid, the original error message is better preserved
- if error is raised by an assertion failure, custom AssertionError messages are provided

other changes involve refactoring of Exceptions to derive from a custom base class, as well as implementation of logging facility

**Comment by worldomonation** [comment]
This task has been more or less completed.
