### ISSUE TITLE
[mozbitbar-31]  __root__.path() may not always return absolute paths

### ISSUE THREAD

**Issue by bclary** [worldomonation/mozbitbar#66]
from the mozbitbar directory if PYTHONPATH is set to it.

python2.7
`>>> import mozbitbar.__root__`
`>>> mozbitbar.__root__.path()`
`'mozbitbar/'`

python3.7
`>>> import mozbitbar.__root__`
`>>> mozbitbar.__root__.path()`
`'/home/mozilla/projects/mozbitbar/mozbitbar/'`

It is conceivable that python3 might also return relative paths depending on if a script is executed with a relative path. https://docs.python.org/3.4/whatsnew/3.4.html#other-language-changes

maybe just use os.path.abspath(__file__) to be safe?

**Comment by worldomonation** [comment]
I am inclined to agree. If I recall correctly, this was to solve the problem where a file I would try to load was not inside or below the current directory. I recall this most commonly manifested in writing unit tests.

Currently the tests are running fine as is, and even though the filesystem-related methods aren't as well tested as I would like, this bodged solution to get the root directory of the repository isn't being used right now.

I'm inclined to remove the whole thing and re-implement it when necessary.

**Comment by bclary** [comment]
Either way is fine.

**Comment by worldomonation** [comment]
Propsed PR #71 which removes all instances of __root__.py code.
