### ISSUE TITLE
[mozbitbar-33]  cli.py parser_arguments should be parse_arguments

### ISSUE THREAD

**Issue by bclary** [worldomonation/mozbitbar#68]
In <https://github.com/worldomonation/mozbitbar/blob/master/mozbitbar/cli.py#L6>, you define the function parser_arguments. I think it would be better named parse_arguments as parse is a verb while parser is a noun. It reads better for me.

**Comment by worldomonation** [comment]
Not sure how this one slipped by, I believe it was originally named `parse_arguments` but became the current form somehow. Thanks for noticing!

In related note, I plan to refactor and add more command line argument support to better reflect how this may be used by the caller.

**Comment by worldomonation** [comment]
#75 fixes the name.

Refactoring of the CLI support is left for another bug.
